// automatically generated by the FlatBuffers compiler, do not modify

package structs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)
type CPUStats struct {
	_tab flatbuffers.Table
}

func GetRootAsCPUStats(buf []byte, offset flatbuffers.UOffsetT) *CPUStats {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CPUStats{}
	x.Init(buf, n + offset)
	return x
}

func (rcv *CPUStats) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CPUStats) ClkTck() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CPUStats) Timestamp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CPUStats) Ctxt() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CPUStats) BTime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CPUStats) Processes() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CPUStats) CPU(obj *CPU, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
	if obj == nil {
		obj = new(CPU)
	}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CPUStats) CPULength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func CPUStatsStart(builder *flatbuffers.Builder) { builder.StartObject(6) }
func CPUStatsAddClkTck(builder *flatbuffers.Builder, ClkTck int16) { builder.PrependInt16Slot(0, ClkTck, 0) }
func CPUStatsAddTimestamp(builder *flatbuffers.Builder, Timestamp int64) { builder.PrependInt64Slot(1, Timestamp, 0) }
func CPUStatsAddCtxt(builder *flatbuffers.Builder, Ctxt int64) { builder.PrependInt64Slot(2, Ctxt, 0) }
func CPUStatsAddBTime(builder *flatbuffers.Builder, BTime int64) { builder.PrependInt64Slot(3, BTime, 0) }
func CPUStatsAddProcesses(builder *flatbuffers.Builder, Processes int64) { builder.PrependInt64Slot(4, Processes, 0) }
func CPUStatsAddCPU(builder *flatbuffers.Builder, CPU flatbuffers.UOffsetT) { builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(CPU), 0) }
func CPUStatsStartCPUVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT { return builder.StartVector(4, numElems, 4)
}
func CPUStatsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT { return builder.EndObject() }
