// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)
type MemInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsMemInfo(buf []byte, offset flatbuffers.UOffsetT) *MemInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MemInfo{}
	x.Init(buf, n + offset)
	return x
}

func (rcv *MemInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MemInfo) Timestamp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MemInfo) Active() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MemInfo) Inactive() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MemInfo) Mapped() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MemInfo) MemAvailable() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MemInfo) MemFree() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MemInfo) MemTotal() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MemInfo) SwapCached() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MemInfo) SwapFree() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MemInfo) SwapTotal() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func MemInfoStart(builder *flatbuffers.Builder) { builder.StartObject(10) }
func MemInfoAddTimestamp(builder *flatbuffers.Builder, Timestamp int64) { builder.PrependInt64Slot(0, Timestamp, 0) }
func MemInfoAddActive(builder *flatbuffers.Builder, Active uint64) { builder.PrependUint64Slot(1, Active, 0) }
func MemInfoAddInactive(builder *flatbuffers.Builder, Inactive uint64) { builder.PrependUint64Slot(2, Inactive, 0) }
func MemInfoAddMapped(builder *flatbuffers.Builder, Mapped uint64) { builder.PrependUint64Slot(3, Mapped, 0) }
func MemInfoAddMemAvailable(builder *flatbuffers.Builder, MemAvailable uint64) { builder.PrependUint64Slot(4, MemAvailable, 0) }
func MemInfoAddMemFree(builder *flatbuffers.Builder, MemFree uint64) { builder.PrependUint64Slot(5, MemFree, 0) }
func MemInfoAddMemTotal(builder *flatbuffers.Builder, MemTotal uint64) { builder.PrependUint64Slot(6, MemTotal, 0) }
func MemInfoAddSwapCached(builder *flatbuffers.Builder, SwapCached uint64) { builder.PrependUint64Slot(7, SwapCached, 0) }
func MemInfoAddSwapFree(builder *flatbuffers.Builder, SwapFree uint64) { builder.PrependUint64Slot(8, SwapFree, 0) }
func MemInfoAddSwapTotal(builder *flatbuffers.Builder, SwapTotal uint64) { builder.PrependUint64Slot(9, SwapTotal, 0) }
func MemInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT { return builder.EndObject() }
