// automatically generated by the FlatBuffers compiler, do not modify

package structs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)
type Nodes struct {
	_tab flatbuffers.Table
}

func GetRootAsNodes(buf []byte, offset flatbuffers.UOffsetT) *Nodes {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Nodes{}
	x.Init(buf, n + offset)
	return x
}

func (rcv *Nodes) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Nodes) Node(obj *Node, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
	if obj == nil {
		obj = new(Node)
	}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Nodes) NodeLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func NodesStart(builder *flatbuffers.Builder) { builder.StartObject(1) }
func NodesAddNode(builder *flatbuffers.Builder, Node flatbuffers.UOffsetT) { builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(Node), 0) }
func NodesStartNodeVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT { return builder.StartVector(4, numElems, 4)
}
func NodesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT { return builder.EndObject() }
